### ISSUE TITLE
How about using a dynamic approach on that?

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/TicTacToeRepo#1]
https://github.com/f-guevara/TicTacToeRepo/blob/dcc6a2ebbc5b3ab1d95b8d13d8644e268b36abb5/TicTactToeGame.cs#L134-L158

A lot of hardcoded checks. You can use the same approach that you did on the slot machine to make that be dynamic.

**Comment by f-guevara** [comment]
Solved
