### ISSUE TITLE
hardcoded strings should not exist in your code

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/TicTacToeRepo#2]
https://github.com/f-guevara/TicTacToeRepo/blob/dcc6a2ebbc5b3ab1d95b8d13d8644e268b36abb5/TicTactToeGame.cs#L48-L60

Your code checks for "y" or "n" and those are the only valid options. Why don't you declare constants for those 2 valid inputs so that they are easy to change if you want to?

**Comment by f-guevara** [comment]
Solved
