### ISSUE TITLE
Those 2 blocks look very similar

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/TicTacToeRepo#4]
https://github.com/f-guevara/TicTacToeRepo/blob/dcc6a2ebbc5b3ab1d95b8d13d8644e268b36abb5/Program.cs#L32-L46

The only thing that is different in both situations is the message that you provide on the DisplayMessage() method. Can this be simplified with one method for example?

**Comment by f-guevara** [comment]
Solved
