### ISSUE TITLE
Are you sure that this compiles?

### ISSUE THREAD

**Issue by AlexKap23** [f-guevara/TicTacToeRepo#5]
https://github.com/f-guevara/TicTacToeRepo/blob/4e4d591ec01b080515860201d43a38820d6f75b7/ConsoleUI.cs#L13-L27

TWO_PLAYERS_MODE is an int and you are comparing it with input which is a string.

Also the 

 DisplayMessage("Invalid input. Please enter {TWO_PLAYERS_MODE } or { PLAY_AGAINST_AI}."); is not compiling because of the double quotes

**Comment by f-guevara** [comment]
Believe it or not, it compiled, but I realise that there was a bug. I fixed it!
